### PR TITLE
add feat/page-not-found page

### PR DESCRIPTION
**Pull request by PriyanshuValiya**
Page Preview..

Screenshot 2024-10-21 193334

### CODE REVIEW

**Review by Saachi26 — APPROVED** [review]

**Comment by PriyanshuValiya** [comment]
@MadhavKrishanGoswami  add this page if all checks were clear, and tags of gssoc-extd..

**Review by MadhavKrishanGoswami — CHANGES_REQUESTED** [review]
It looks like the lucide-react library was added but not used in the project. Would you mind removing it to keep things clean and efficient? Thanks a lot! 🙌

**Comment by PriyanshuValiya** [comment]
@MadhavKrishanGoswami You mean to say remove the lucide library or not need this whole page ?

**Comment by MadhavKrishanGoswami** [comment]
I noticed we haven't used the lucide-react library anywhere in the project, and I don't think you used it either. Could you let me know why you added it added?

**Comment by PriyanshuValiya** [comment]
Ok, I will add some icon and raise PR again in some hours..

**Pull request closed without merging**
