### PR TITLE
Added the program section 

### PR DESCRIPTION
**Pull request by Aman-G-upta**
Done with the changes.
Please merge it @MadhavKrishanGoswami

### CODE REVIEW

**Review by MadhavKrishanGoswami — CHANGES_REQUESTED** [review]
I noticed that the logos aren’t showing up correctly. Could you please help me fix this?

**Comment by Aman-G-upta** [comment]
Could you please explain the problem in more detail? @MadhavKrishanGoswami

**Comment by MadhavKrishanGoswami** [comment]
Screenshot 2024-11-03 at 11 25 09 PM
the images are not visible

**Comment by Aman-G-upta** [comment]
In my side everything is fine 
image

**Review by MadhavKrishanGoswami — APPROVED** [review]

**Pull request merged**
