### PR TITLE
add execution feat

### PR DESCRIPTION
**Pull request by ifeelsam**
added the code execution feature use piston API and restricted the modules use

### CODE REVIEW

**Comment by MadhavKrishanGoswami** [comment]
Hi @ifeelsam,  

Thank you so much for your pull request! 🙌 I really appreciate your contribution. I’ll review it shortly and update you.

Thanks again for your effort!

**Comment by ifeelsam** [comment]
@MadhavKrishanGoswami please take your time, In the meantime, I will focus on including runtime and other relevant factors

**Review by MadhavKrishanGoswami — CHANGES_REQUESTED** [review]
Hey, thanks for your work on this! 🙌 I’ve tested it, but it seems the output isn’t showing. Could you please take another look at it? Also, apologies for the delayed review. Let me know if you need any more details!

**Comment by ifeelsam** [comment]
it seems to be working fine 
i can add a video if you want

**Review by MadhavKrishanGoswami — APPROVED** [review]
So sorry about that, I think it was a socket issue on my side. It's working fine now, and I believe we can merge it! 👍

**Comment by MadhavKrishanGoswami** [comment]
Thank you so much for your contribution! 🙌 Your effort is greatly appreciated, Looking forward to more awesome contributions from you! 🚀

**Pull request merged**
