### PR TITLE
Readme Updation | Issue #9

### PR DESCRIPTION
**Pull request by Shariq2003**
Update and readme file completely and also added the architecture image of this project for better understanding to user.
Completed #9 

https://github.com/user-attachments/assets/fba19f33-f3b1-4f48-bff5-a668e270fce6

### CODE REVIEW

**Comment by MadhavKrishanGoswami** [comment]
hey @Shariq2003 The README looks perfect—clear, well-organized, and easy to follow. 💯

Just one minor suggestion: we could remove the AI-generated image to keep the README cleaner and more focused on the content.

Other than that, it's spot on. Amazing job! 🎉

**Comment by Shariq2003** [comment]
> hey @Shariq2003 The README looks perfect—clear, well-organized, and easy to follow. 💯
> 
> Just one minor suggestion: we could remove the AI-generated image to keep the README cleaner and more focused on the content.
> 
> Other than that, it's spot on. Amazing job! 🎉

let me remove that. sir

**Comment by Shariq2003** [comment]
@MadhavKrishanGoswami check now

**Review by MadhavKrishanGoswami — APPROVED** [review]

**Comment by MadhavKrishanGoswami** [comment]
Thank you for your contribution @Shariq2003 !
cheers 🥂

**Comment by Shariq2003** [comment]
@MadhavKrishanGoswami please add label of level 
and also assign

**Pull request merged**
