### PR TITLE
Create contributing.md file

### PR DESCRIPTION
**Pull request by AnujSaha0111**
Created CONTRIBUTING.md with following structure:

1. Setting up the project: Instructions on forking the repository, cloning, and creating a new branch.
2. Code of Conduct: Reference to a code of conduct for maintaining a respectful community.
3. Issues: Guidelines for reporting bugs and requesting features.
4. Pull Requests: Instructions on how to submit a pull request, including guidelines for descriptions and linking issues.
5. Commit Messages: Standards for writing clear commit messages.
6. Coding Guidelines: Information about the tech stack and coding style to follow.
7. Development Workflow: Steps for running the development environment, testing, and building the project.
8. License: Information regarding the project's license.

### CODE REVIEW

**Review by MadhavKrishanGoswami — CHANGES_REQUESTED** [review]
Hello @AnujSaha0111, Thank you for the effort! The style of the file looks good, but I noticed a couple of things:
1. We don't use Python in our project.
2. The tech stack mentioned is incorrect.

Could you please check the **README.md** file to confirm our correct tech stack and workflow? Once updated, everything else seems great!

Thanks again for your contribution!

Cheers🥂

**Comment by AnujSaha0111** [comment]
Made changes, please review it

**Review by MadhavKrishanGoswami — CHANGES_REQUESTED** [review]
Everything looks good! However, could you please remove the Coding Guidelines section and Explanation ? Once that's done, we can go ahead with this.

Thanks!

**Comment by AnujSaha0111** [comment]
removing coding guideline section will also remove tech stack section which is subsection of coding guidelines
will I remove it?

**Comment by MadhavKrishanGoswami** [comment]
Oh, I’m sorry! Just the explanation part needs to be removed. Once that’s done, we can go ahead with this!

Thanks!

**Comment by AnujSaha0111** [comment]
Done with it.

**Review by MadhavKrishanGoswami — APPROVED** [review]
Thank you for your contribution @AnujSaha0111  !
cheers 🥂

**Comment by AnujSaha0111** [comment]
but, it is unmerged
Please add gssoc-ext label

**Comment by MadhavKrishanGoswami** [comment]
Really sorry for the confusion, and thank you for your contribution, @AnujSaha0111! 🙌

**Pull request merged**
