### PR TITLE
Improved Form Ui

### PR DESCRIPTION
**Pull request by iamsohelx**
@MadhavKrishanGoswami I Have Improved the ui of Forms

## Features

- Changed the ui
- Added Fonts
- Copy button is only visible when you generate room code

## Screenshot

Happy

**Please give label Before merging it : ) [ hacktoberfest-accepted - gssoc-ext - level3 ]**
**Thank you : )**

### CODE REVIEW

**Comment by MadhavKrishanGoswami** [comment]
Hello! @iamsohelx, just one more thing — I think both the colors are different. Could you make them the same? It looks a little odd.

**Comment by iamsohelx** [comment]
> Hello! @iamsohelx, just one more thing — I think both the colors are different. Could you make them the same? It looks a little odd.

sad

it is okay now? Can i commit changes? @MadhavKrishanGoswami

**Comment by iamsohelx** [comment]
@MadhavKrishanGoswami Could you please add atleast level 2 label. because i have done 2 things here

- Changed the ui
- Made the copy button visible only when the code is generated

Initially you assigned level 3 label, now you're giving level 1, please atleast give level 2. brother please.
And also add the [ hacktoberfest-accepted ] label.

**Comment by iamsohelx** [comment]
@Saachi26 Thank you so much Saachi. please also add hacktoberfest-accepted label

**Comment by MadhavKrishanGoswami** [comment]
Hey @iamsohelx , thank you so much for your contribution! Apologies for the confusion — the Level 1 label was added by mistake. I've corrected it to Level 3, and I've also added the [hacktoberfest-accepted] label. Appreciate your understanding and effort!

**Comment by iamsohelx** [comment]
> Hey @iamsohelx , thank you so much for your contribution! Apologies for the confusion — the Level 1 label was added by mistake. I've corrected it to Level 3, and I've also added the [hacktoberfest-accepted] label. Appreciate your understanding and effort!

Thank you thank you so muchhh brother. Thanks a lot.

**Pull request merged**
